apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sktech-rc
spec:
  replicas: 2
  selector:
    matchExpression:
    - app: backend
  template:
    metadata:
      name: sktech-pod
      labels:
        app: backend
    spec:
      containers:
      - name:  sktech-con
        image:  ubuntu:22.04
        command: ["bin/bash","-c","while true;do echo Hello SKTech;sleep 3;done"]