apiVersion: apps/v1
kind: Deployment
metadata:
  name: sktech-rc
spec:
  replicas: 2
  selector:
    matchExpression:
    - app: backend
  template:
    metadata:
      name: sktech-pod
      labels:
        app: backend
    spec:
      containers:
      - name:  sktech-con
        image:  ubuntu:18.04
        command: ["bin/bash","-c","while true;do echo Hello SKTech;sleep 3;done"]

#################################

        image:  ubuntu:22.04
        command: ["bin/bash","-c","while true;do echo Hello Students;sleep 3;done"]

#################################
kubectl rollout history deploy sktech-deploy 

kubectl rollout undo deploy sktech-deploy 
kubectl rollout undo deploy sktech-deploy --to-revision=1 