# Service : ClusterIP on Deployment Object
---
apiVersion: v1
kind: Service
metadata:
  name: sktech-svc
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - port: 80              # Container Port 
    targetPort: 80        # Pod Port

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sktech-rc
spec:
  replicas: 2
  selector:
    matchExpression:
    - app: frontend
  template:
    metadata:
      name: sktech-pod
      labels:
        app: frontend
    spec:
      containers:
      - name:  sktech-con
        image: httpd:2.4.57